# Generated by Django 3.1.7 on 2021-03-14 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustPhone', models.IntegerField(verbose_name='Phone')),
                ('CustCountry', models.CharField(max_length=60, verbose_name='Country')),
                ('CustCity', models.CharField(max_length=60, verbose_name='City')),
                ('CustLocality', models.CharField(max_length=60, verbose_name='Locality')),
                ('CustZipcode', models.CharField(max_length=15, verbose_name='Zipcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
