# Generated by Django 3.1.7 on 2021-04-04 13:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210316_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CustCountry',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
