# Generated by Django 3.1.7 on 2021-03-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostImg', models.ImageField(upload_to='blog_images')),
                ('Postitle', models.CharField(max_length=100, verbose_name='Title')),
                ('Possubject', models.TextField(verbose_name='Subject')),
                ('Posadd', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add at')),
                ('Posupdate', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('Posuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PComtitle', models.CharField(max_length=100, verbose_name='Title')),
                ('PComessage', models.TextField(verbose_name='Message')),
                ('PComadd', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add at')),
                ('PComupdate', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('PCompost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post', verbose_name='Post')),
                ('PComuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
