# Generated by Django 3.1.7 on 2021-03-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='PComtitle',
        ),
    ]
