# Generated by Django 3.1.7 on 2021-03-21 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210319_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosvId', models.CharField(max_length=200, verbose_name='Video')),
                ('Posvtitle', models.CharField(max_length=100, verbose_name='Title')),
                ('Posvsubject', models.TextField(verbose_name='Subject')),
                ('Posvadd', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add at')),
                ('Posvupdate', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('Posvuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postvideo', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostVideoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PVComessage', models.TextField(verbose_name='Message')),
                ('PVComadd', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Add at')),
                ('PVComupdate', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('PVCompost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocomment', to='blog.video', verbose_name='comment')),
                ('PVComuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocomment', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
