# Generated by Django 3.1.7 on 2021-03-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210321_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='posvimg',
            field=models.ImageField(default='default.jpgs', upload_to='postvideo_img'),
        ),
    ]
