# Generated by Django 3.1.7 on 2021-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210321_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headertext', models.CharField(max_length=25)),
                ('headertitle', models.CharField(max_length=100)),
                ('itemvideourl', models.URLField()),
                ('headerimg', models.ImageField(upload_to='blog-review-img')),
                ('price', models.IntegerField()),
                ('reviewimg1', models.ImageField(upload_to='blog-review_img')),
                ('reviewtitle1', models.CharField(max_length=30)),
                ('reviewdescription1', models.TextField()),
                ('reviewimg2', models.ImageField(upload_to='blog-review_img')),
                ('reviewtitle2', models.CharField(max_length=30)),
                ('reviewdescription2', models.TextField()),
            ],
        ),
    ]
