# Generated by Django 3.1.7 on 2021-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogreview_reviewdescription3'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreview',
            name='createat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogreview',
            name='updateat',
            field=models.DateTimeField(auto_now=True, verbose_name='Update at'),
        ),
    ]
