# Generated by Django 3.1.7 on 2021-03-22 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('discrption', models.TextField(verbose_name='Discrption')),
                ('Brand', models.CharField(choices=[('hp', 'HP'), ('asus', 'ASUS'), ('lenovo', 'Lenovo'), ('apple', 'Apple')], max_length=20, verbose_name='Brand')),
                ('prodtype', models.CharField(choices=[('lap', 'Laptops'), ('tap', 'Taplet'), ('hyp', 'Hybrid')], max_length=15, verbose_name='Product type')),
                ('os', models.CharField(max_length=15, verbose_name='Operating system')),
                ('Process_type', models.CharField(max_length=20, verbose_name='Processor type')),
                ('Graphic_quality', models.CharField(max_length=20, verbose_name='Graphics')),
                ('screen_size', models.IntegerField(default=0, verbose_name='Screen Size')),
                ('tag1', models.CharField(choices=[('busi', 'Business'), ('home', 'Home'), ('mobil', 'Mobility'), ('power', 'Powerfull'), ('game', 'Gaming')], max_length=20, verbose_name='Tags')),
                ('tag2', models.CharField(blank=True, choices=[('busi', 'Business'), ('home', 'Home'), ('mobil', 'Mobility'), ('power', 'Powerfull'), ('game', 'Gaming')], max_length=20, null=True, verbose_name='Tags')),
                ('tag3', models.CharField(blank=True, choices=[('busi', 'Business'), ('home', 'Home'), ('mobil', 'Mobility'), ('power', 'Powerfull'), ('game', 'Gaming')], max_length=20, null=True, verbose_name='Tags')),
                ('selling_price', models.IntegerField(default=0, verbose_name='Selling Price')),
                ('discount_price', models.IntegerField(default=0, verbose_name='Discount Price')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Update At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(max_length=25, verbose_name='Proprty')),
                ('prop_discrption', models.CharField(max_length=250, verbose_name='discrption of the Proprty')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop', to='ecommerce.product')),
            ],
        ),
        migrations.CreateModel(
            name='product_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
