# Generated by Django 3.1.7 on 2021-03-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(max_length=20, verbose_name='Operating system'),
        ),
    ]
