# Generated by Django 3.1.7 on 2021-03-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210322_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=22, upload_to='product_img', verbose_name='Img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_comments',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='product_property',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='product_property',
            name='prop',
            field=models.CharField(max_length=25, verbose_name='Property'),
        ),
        migrations.CreateModel(
            name='Product_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product_img', verbose_name='Img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='ecommerce.product')),
            ],
        ),
    ]
