# Generated by Django 3.1.7 on 2021-03-22 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_auto_20210322_0957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_comments',
            new_name='productcomments',
        ),
        migrations.RenameModel(
            old_name='Product_img',
            new_name='Productimg',
        ),
        migrations.RenameModel(
            old_name='Product_property',
            new_name='Productproperty',
        ),
    ]
