# Generated by Django 3.1.7 on 2021-03-22 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_auto_20210322_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productcomments',
            new_name='productComment',
        ),
    ]
