# Generated by Django 3.1.7 on 2021-03-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20210322_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(default=0, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=0, verbose_name='Selling Price'),
        ),
    ]
