# Generated by Django 3.1.7 on 2021-03-25 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0008_auto_20210322_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
