# Generated by Django 3.1.7 on 2021-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210325_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag1',
            field=models.CharField(choices=[('Business', 'Business'), ('Home', 'Home'), ('Mobility', 'Mobility'), ('Powerfull', 'Powerfull'), ('Gaming', 'Gaming')], max_length=20, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag2',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Mobility', 'Mobility'), ('Powerfull', 'Powerfull'), ('Gaming', 'Gaming')], max_length=20, null=True, verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag3',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Home', 'Home'), ('Mobility', 'Mobility'), ('Powerfull', 'Powerfull'), ('Gaming', 'Gaming')], max_length=20, null=True, verbose_name='Tags'),
        ),
    ]
