# Generated by Django 3.1.7 on 2021-03-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20210328_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag3',
        ),
    ]
