# Generated by Django 3.1.7 on 2021-03-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20210328_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_video', verbose_name='Video'),
        ),
    ]
