# Generated by Django 3.1.7 on 2021-03-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
        migrations.AddField(
            model_name='product',
            name='video_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Youtube Video Id'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_img',
            field=models.ImageField(blank=True, null=True, upload_to='product_video_img', verbose_name='Video Img'),
        ),
    ]
