# Generated by Django 3.1.7 on 2021-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
