# Generated by Django 3.1.7 on 2021-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20210401_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(blank=True, null=True, upload_to='gellary_img', verbose_name='Image')),
                ('video', models.CharField(blank=True, max_length=50, null=True, verbose_name='or Video Id')),
            ],
        ),
    ]
