# Generated by Django 3.1.7 on 2021-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_gallert'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallert',
            name='video_img',
            field=models.ImageField(blank=True, null=True, upload_to='gellary_img', verbose_name='Img of the video'),
        ),
    ]
