# Generated by Django 3.1.7 on 2021-04-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_auto_20210401_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_img',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_preview',
            field=models.ImageField(default=1, upload_to='gellary_img', verbose_name='Preview Image'),
            preserve_default=False,
        ),
    ]
