# Generated by Django 3.1.7 on 2021-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20210402_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img_preview',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(default=1, upload_to='gellary_img', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.CharField(default=' ', max_length=50, verbose_name='or Video Id'),
        ),
    ]
