# Generated by Django 3.1.7 on 2021-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20210402_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='source',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'Vimeo')], default='youtube', max_length=10),
        ),
    ]
