# Generated by Django 3.1.7 on 2021-04-04 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210404_1329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0026_gallery_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='source',
            field=models.CharField(choices=[('youtube', 'youtube'), ('vimeo', 'Vimeo')], default='youtube', max_length=10, verbose_name='Video source'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_data', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cansel', 'Cansel')], default='panding', max_length=30)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
