# Generated by Django 3.1.7 on 2021-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_auto_20210404_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delevery_option',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
